### ISSUE TITLE
NPM Install Error @react-admin/ra-navigation

### ISSUE THREAD

**Issue by CasualEngineerZombie** [marmelab/react-admin-helpdesk#1]
### Describe the bug
When trying to run npm install on this when cloned via `git clone https://github.com/marmelab/react-admin-helpdesk.git`, I'm encountering a 401 Unauthorized error.

### To Reproduce

1. Clone the repository
2. Run npm install
3. See error

### Expected behavior
The expected behavior is that npm install should successfully install all dependencies without errors.

### Error Details
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://registry.marmelab.com/download/@react-admin/ra-navigation/4.3.3/502e164b9c107b640a8391b7804121ebdb08a4a5

**Comment by fzaninotto** [comment]
See [the README](https://github.com/marmelab/react-admin-helpdesk#running-the-demo-locally):

> This application uses **React-admin Enterprise Edition** packages, so you'll need a valid subscription to run it. Check out the [Enterprise Edition documentation](https://marmelab.com/ra-enterprise/) for more information.
